# Generated by Django 3.0.14 on 2021-12-11 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20211207_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='modules',
            new_name='module',
        ),
    ]
